### ISSUE TITLE
Change text of buttons

### ISSUE THREAD

**Issue by Okami-x-Senpai** [msayan/tutorial-view#8]
How do I change the text of the buttons ?. When using the setPrevText ("") method; This throws me an error when opening the activity.

**Comment by msayan** [comment]
Can you share the exception?

**Comment by Okami-x-Senpai** [comment]
2019-02-17 11:41:01.332 4833-4833/network.wolfnginx.okami E/AndroidRuntime: FATAL EXCEPTION: main
    Process: network.wolfnginx.okami, PID: 4833
    java.lang.RuntimeException: Unable to start activity ComponentInfo{network.wolfnginx.okami/network.wolfnginx.okami.main.Tutorial}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.hololo.tutorial.library.TutorialActivity.controlPermission(TutorialActivity.java:217)
        at com.hololo.tutorial.library.TutorialActivity.controlPosition(TutorialActivity.java:111)
        at com.hololo.tutorial.library.TutorialActivity.setPrevText(TutorialActivity.java:250)
        at network.wolfnginx.okami.main.Tutorial.onCreate(Tutorial.java:26)
        at android.app.Activity.performCreate(Activity.java:7084)
        at android.app.Activity.performCreate(Activity.java:7075)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6635) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by msayan** [comment]
Thank you. Tomorrow will fix it and release new version

**Comment by Okami-x-Senpai** [comment]
¡Thanks! :smile:

**Comment by Okami-x-Senpai** [comment]
Also a suggestion: Could you make the Dots more Material Design and the Buttons too? That the Dots have a transition like the Dots of the notification bar of Android Pie or Android Oreo, and that the buttons can be added a Custom Background or that they were more material design

_Enviado desde mi Redmi  Note  6  Pro usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by msayan** [comment]
Can you try with v1.0.9 version

**Comment by msayan** [comment]
> Also a suggestion: Could you make the Dots more Material Design and the Buttons too? That the Dots have a transition like the Dots of the notification bar of Android Pie or Android Oreo, and that the buttons can be added a Custom Background or that they were more material design
> 
> _Enviado desde mi Redmi Note 6 Pro usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

You can make the changes and send PR to me :)

**Comment by itzThiefz-exe** [comment]
Gradle does not recognize me that version and prevents me from implementing

**Comment by itzThiefz-exe** [comment]
Help me?

**Comment by Okami-x-Senpai** [comment]
Work It works perfect, thank you very much sir! This issue has been fixed.

**Comment by ekalburcu** [comment]
@msayan Hocam merhabalar, bu arkadaşın sorununa çok benzer bir sorunla muzdaribim ben de, bir haftadır ne kadar uğraştıysam çözemedim, gerekli hata bilgilerini ve uygulamanın linkini mail adresiniz üzerinden yollasam, müsait olduğunuzda bir bakabilir misiniz? Çok memnun olurum, teşekkürler
